### ISSUE TITLE
Fresh install- automatically scrolls to the contact form at the bottom on page load

### ISSUE THREAD

**Issue by rossity** [getgrav/grav-theme-agency#12]
Title- i thought it was something to do with my code but even on a fresh install the page automatically scrolls to the contact form at the bottom when loading/refreshing the page

**Comment by rossity** [comment]
fixed it by commenting out line 44 in user\plugins\form\templates\forms\default\field.html.twig:

**Comment by elFani** [comment]
I'm getting the same issue but the line 44 comment isn't working.

Obviously, some sort of bug that with the autfocus of the first form field. Interesting that Grav doesn't have a form on their demo page for this theme...

EDIT: just tried commenting out line 44 again and it worked

EDIT 2: better solution is to just comment/remove autofocus: 'on' in the portfolio.md file. autofocus is turned on in the first field on the fields: list

**Comment by flaviocopes** [comment]
Your form page header had autofocus enabled on the Name field.

It was the default in the Agency Site skeleton up to now, if you were using that. 
I just issued an updated which contains a fix from @OleVik https://github.com/getgrav/grav-skeleton-agency-site/commit/2e04ab860b0a1bd4d69b168eadc26f0c0dcc4ddd
