### ISSUE TITLE
Latest update issues

### ISSUE THREAD

**Issue by dennisliideo** [getgrav/grav-theme-agency#5]
Hi,
I recently updated my site and all of the sudden the navigation is dublicated and my google maps plugin does not appear. We also had a short video as the header image but it does not show up after the update. Any ideas what might have gone wrong? We only pressed the update link on the theme image on Grav admin panel.

**Comment by hexplor** [comment]
Looks like update messed up the install somehow. Did you try downloading the theme separately and updating manually ? You can also send me whole website to karol@rockettheme.com and I can take a look what's wrong.

**Comment by dennisliideo** [comment]
Hi! Thank you for you response. I updated the theme on the Grav Admin panel, that might have messed up some of the code. I could share you our ftp details thru email and if you could have a look what went wrong? That would help us a lot!

**Comment by hexplor** [comment]
Sure :) go on :)

**Comment by hexplor** [comment]
Check now. I suppose this is how it was looking before upgrade right ? I commented following part in base.html.twig:

``` twig
{% block header_navigation %}
    {% include 'partials/navigation.html.twig' %}
  {% endblock %}
```

You've made some changes in the theme and this line is present there by default.

**Comment by dennisliideo** [comment]
The navigation is working now. 

A few minor issues:
1. The logo is not scaling correctly (responsive)
2. Google Maps isn't visible for some reason
3. "Our team" section portrait image was align to the right with the text block.
4. Contact form had more contacts details, such as my number etc.
5. We also had a video on the header which is not playing after the update

I guess it was a mistake updating the theme is we had some custom code in it. :) but thanks you for the help.

**Comment by hexplor** [comment]
Thing is. I don't know how did you customized it before :( Each update replaces old files with newer ones. It's not preserving your changes if you modified the theme. I am afraid you may need to redo your modifications. 
I can also suggest you one thing for a future. This is how i do it. Grav is really easy to deploy/duplicate. Before updating a live site,  it's always better to test it locally, and then if everything works, perform update on live site..
