### ISSUE TITLE
Agency theme skeleton form's not working 

### ISSUE THREAD

**Issue by basikthings** [getgrav/grav-theme-agency#6]
Hi, 

I've been having the toughest time trying to get the forms to show up properly in the agency theme skeleton page. When I go to "simple_form.yaml" to set "enabled: true" I get the following error. 

E_COMPILE_ERROR - Access level to Grav\Plugin\Simple_FormPlugin::mergeConfig() must be protected (as in class Grav\Common\Plugin) or weaker

I'm not much of a web programmer and can't really debug this myself. Would it be possible to update the skeleton to fix the issue?

**Comment by flaviocopes** [comment]
Looks like the skeleton ships **Simple Form 1.2.1** which has issues with the current Grav. Latest release is **1.3.2** and has solved the problem. 

Updating the plugin through CLI (`bin/gpm update`) fixes the problem. 

@rhukster does the skeleton needs to be regenerated to use the latest available release of Simple Form?

**Comment by basikthings** [comment]
I updated the simple form, but I think a few things need to change for the theme skeleton as well since I couldn't get the form to pop up.

**Comment by flaviocopes** [comment]
Check the plugin is enabled, I got it working fine

**Comment by basikthings** [comment]
Thanks! I updated with bin/gpm and worked fine.

On Thu, Mar 10, 2016 at 1:14 AM, Flavio Copes notifications@github.com
wrote:

> Check the plugin is enabled, I got it working fine
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/getgrav/grav-theme-agency/issues/6#issuecomment-194746893
> .

## 

Bryan
